In [1]:
import numpy as np
from micrograd.engine import Tensor
from model import MLP
import micrograd.optim as optim
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import KNNImputer

In [18]:
losses = []

np.random.seed(37) # for reproducibility

# dataset
df = pd.read_csv('penguins.csv')

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Species         150 non-null    str
 1   CulmenLength    148 non-null    float64
 2   CulmenDepth     148 non-null    float64
 3   FlipperLength   148 non-null    float64
 4   OriginLocation  150 non-null    str
 5   BodyMass        148 non-null    float64
dtypes: float64(4), str(2)
memory usage: 7.2 KB

In [20]:
df.head()

  Species  CulmenLength  CulmenDepth  FlipperLength OriginLocation  BodyMass
0  Adelie          39.1         18.7          181.0      Torgersen    3750.0
1  Adelie          39.5         17.4          186.0      Torgersen    3800.0
2  Adelie          40.3         18.0          195.0      Torgersen    3250.0
3  Adelie           NaN          NaN            NaN      Torgersen       NaN
4  Adelie          36.7         19.3          193.0      Torgersen    3450.0

In [21]:
df['Species'] = df['Species'].map({'Adelie': 0, 'Chinstrap': 1, 'Gentoo': 2})

In [25]:
df['OriginLocation'] = df['OriginLocation'].map({'Torgersen': 0, 'Biscoe': 1, 'Dream': 2})

In [26]:
df.dropna(inplace=True)

In [28]:
df.head()

   Species  CulmenLength  CulmenDepth  FlipperLength  OriginLocation  BodyMass
0        0          39.1         18.7          181.0               0    3750.0
1        0          39.5         17.4          186.0               0    3800.0
2        0          40.3         18.0          195.0               0    3250.0
4        0          36.7         19.3          193.0               0    3450.0
5        0          39.3         20.6          190.0               0    3650.0

In [29]:
y = df['Species'].values
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [30]:
x = df.drop('Species', axis=1).values

In [31]:
x

array([[3.910e+01, 1.870e+01, 1.810e+02, 0.000e+00, 3.750e+03],
       [3.950e+01, 1.740e+01, 1.860e+02, 0.000e+00, 3.800e+03],
       [4.030e+01, 1.800e+01, 1.950e+02, 0.000e+00, 3.250e+03],
       [3.670e+01, 1.930e+01, 1.930e+02, 0.000e+00, 3.450e+03],
       [3.930e+01, 2.060e+01, 1.900e+02, 0.000e+00, 3.650e+03],
       [3.890e+01, 1.780e+01, 1.810e+02, 0.000e+00, 3.625e+03],
       [3.920e+01, 1.960e+01, 1.950e+02, 0.000e+00, 4.675e+03],
       [3.410e+01, 1.810e+01, 1.930e+02, 0.000e+00, 3.475e+03],
       [4.200e+01, 2.020e+01, 1.900e+02, 0.000e+00, 4.250e+03],
       [3.780e+01, 1.710e+01, 1.860e+02, 0.000e+00, 3.300e+03],
       [3.780e+01, 1.730e+01, 1.800e+02, 0.000e+00, 3.700e+03],
       [4.110e+01, 1.760e+01, 1.820e+02, 0.000e+00, 3.200e+03],
       [3.860e+01, 2.120e+01, 1.910e+02, 0.000e+00, 3.800e+03],
       [3.460e+01, 2.110e+01, 1.980e+02, 0.000e+00, 4.400e+03],
       [3.660e+01, 1.780e+01, 1.850e+02, 0.000e+00, 3.700e+03],
       [3.870e+01, 1.900e+01, 1.950e+02, 0.000e+00, 3.450e+03],
       [4.250e+01, 2.070e+01, 1.970e+02, 0.000e+00, 4.500e+03],
       [3.440e+01, 1.840e+01, 1.840e+02, 0.000e+00, 3.325e+03],
       [4.600e+01, 2.150e+01, 1.940e+02, 0.000e+00, 4.200e+03],
       [3.780e+01, 1.830e+01, 1.740e+02, 1.000e+00, 3.400e+03],
       [3.770e+01, 1.870e+01, 1.800e+02, 1.000e+00, 3.600e+03],
       [3.590e+01, 1.920e+01, 1.890e+02, 1.000e+00, 3.800e+03],
       [3.820e+01, 1.810e+01, 1.850e+02, 1.000e+00, 3.950e+03],
       [3.880e+01, 1.720e+01, 1.800e+02, 1.000e+00, 3.800e+03],
       [3.530e+01, 1.890e+01, 1.870e+02, 1.000e+00, 3.800e+03],
       [4.060e+01, 1.860e+01, 1.830e+02, 1.000e+00, 3.550e+03],
       [4.050e+01, 1.790e+01, 1.870e+02, 1.000e+00, 3.200e+03],
       [3.790e+01, 1.860e+01, 1.720e+02, 1.000e+00, 3.150e+03],
       [4.050e+01, 1.890e+01, 1.800e+02, 1.000e+00, 3.950e+03],
       [3.950e+01, 1.670e+01, 1.780e+02, 2.000e+00, 3.250e+03],
       [3.720e+01, 1.810e+01, 1.780e+02, 2.000e+00, 3.900e+03],
       [3.950e+01, 1.780e+01, 1.880e+02, 2.000e+00, 3.300e+03],
       [4.090e+01, 1.890e+01, 1.840e+02, 2.000e+00, 3.900e+03],
       [3.640e+01, 1.700e+01, 1.950e+02, 2.000e+00, 3.325e+03],
       [3.920e+01, 2.110e+01, 1.960e+02, 2.000e+00, 4.150e+03],
       [3.880e+01, 2.000e+01, 1.900e+02, 2.000e+00, 3.950e+03],
       [4.220e+01, 1.850e+01, 1.800e+02, 2.000e+00, 3.550e+03],
       [3.760e+01, 1.930e+01, 1.810e+02, 2.000e+00, 3.300e+03],
       [3.980e+01, 1.910e+01, 1.840e+02, 2.000e+00, 4.650e+03],
       [3.650e+01, 1.800e+01, 1.820e+02, 2.000e+00, 3.150e+03],
       [4.080e+01, 1.840e+01, 1.950e+02, 2.000e+00, 3.900e+03],
       [3.600e+01, 1.850e+01, 1.860e+02, 2.000e+00, 3.100e+03],
       [4.410e+01, 1.970e+01, 1.960e+02, 2.000e+00, 4.400e+03],
       [3.700e+01, 1.690e+01, 1.850e+02, 2.000e+00, 3.000e+03],
       [3.960e+01, 1.880e+01, 1.900e+02, 2.000e+00, 4.600e+03],
       [4.110e+01, 1.900e+01, 1.820e+02, 2.000e+00, 3.425e+03],
       [3.750e+01, 1.890e+01, 1.790e+02, 2.000e+00, 2.975e+03],
       [3.600e+01, 1.790e+01, 1.900e+02, 2.000e+00, 3.450e+03],
       [4.230e+01, 2.120e+01, 1.910e+02, 2.000e+00, 4.150e+03],
       [4.650e+01, 1.790e+01, 1.920e+02, 2.000e+00, 3.500e+03],
       [5.000e+01, 1.950e+01, 1.960e+02, 2.000e+00, 3.900e+03],
       [5.130e+01, 1.920e+01, 1.930e+02, 2.000e+00, 3.650e+03],
       [4.540e+01, 1.870e+01, 1.880e+02, 2.000e+00, 3.525e+03],
       [5.270e+01, 1.980e+01, 1.970e+02, 2.000e+00, 3.725e+03],
       [4.520e+01, 1.780e+01, 1.980e+02, 2.000e+00, 3.950e+03],
       [4.610e+01, 1.820e+01, 1.780e+02, 2.000e+00, 3.250e+03],
       [5.130e+01, 1.820e+01, 1.970e+02, 2.000e+00, 3.750e+03],
       [4.600e+01, 1.890e+01, 1.950e+02, 2.000e+00, 4.150e+03],
       [5.130e+01, 1.990e+01, 1.980e+02, 2.000e+00, 3.700e+03],
       [4.660e+01, 1.780e+01, 1.930e+02, 2.000e+00, 3.800e+03],
       [5.170e+01, 2.030e+01, 1.940e+02, 2.000e+00, 3.775e+03],
       [4.700e+01, 1.730e+01, 1.850e+02, 2.000e+00, 3.700e+03],
       [5.200e+01, 1.810e+01, 2.010e+02, 2.000e+00, 4.050e+03],
       [4.590e+01, 1.710e+01, 1.900e+02, 2.000e+00, 3.575e+03],
       [5.050e+01, 1.960e+01, 2.010e+02, 2.000e+00, 4.050e+03],
       [5.030e+01, 2.000e+01, 1.970e+02, 2.000e+00, 3.300e+03],
       [5.800e+01, 1.780e+01, 1.810e+02, 2.000e+00, 3.700e+03],
       [4.640e+01, 1.860e+01, 1.900e+02, 2.000e+00, 3.450e+03],
       [4.920e+01, 1.820e+01, 1.950e+02, 2.000e+00, 4.400e+03],
       [4.240e+01, 1.730e+01, 1.810e+02, 2.000e+00, 3.600e+03],
       [4.850e+01, 1.750e+01, 1.910e+02, 2.000e+00, 3.400e+03],
       [4.320e+01, 1.660e+01, 1.870e+02, 2.000e+00, 2.900e+03],
       [5.060e+01, 1.940e+01, 1.930e+02, 2.000e+00, 3.800e+03],
       [4.670e+01, 1.790e+01, 1.950e+02, 2.000e+00, 3.300e+03],
       [5.200e+01, 1.900e+01, 1.970e+02, 2.000e+00, 4.150e+03],
       [5.050e+01, 1.840e+01, 2.000e+02, 2.000e+00, 3.400e+03],
       [4.950e+01, 1.900e+01, 2.000e+02, 2.000e+00, 3.800e+03],
       [4.640e+01, 1.780e+01, 1.910e+02, 2.000e+00, 3.700e+03],
       [5.280e+01, 2.000e+01, 2.050e+02, 2.000e+00, 4.550e+03],
       [4.090e+01, 1.660e+01, 1.870e+02, 2.000e+00, 3.200e+03],
       [5.420e+01, 2.080e+01, 2.010e+02, 2.000e+00, 4.300e+03],
       [4.250e+01, 1.670e+01, 1.870e+02, 2.000e+00, 3.350e+03],
       [5.100e+01, 1.880e+01, 2.030e+02, 2.000e+00, 4.100e+03],
       [4.970e+01, 1.860e+01, 1.950e+02, 2.000e+00, 3.600e+03],
       [4.750e+01, 1.680e+01, 1.990e+02, 2.000e+00, 3.900e+03],
       [4.760e+01, 1.830e+01, 1.950e+02, 2.000e+00, 3.850e+03],
       [5.200e+01, 2.070e+01, 2.100e+02, 2.000e+00, 4.800e+03],
       [4.690e+01, 1.660e+01, 1.920e+02, 2.000e+00, 2.700e+03],
       [5.350e+01, 1.990e+01, 2.050e+02, 2.000e+00, 4.500e+03],
       [4.900e+01, 1.950e+01, 2.100e+02, 2.000e+00, 3.950e+03],
       [4.620e+01, 1.750e+01, 1.870e+02, 2.000e+00, 3.650e+03],
       [5.090e+01, 1.910e+01, 1.960e+02, 2.000e+00, 3.550e+03],
       [4.550e+01, 1.700e+01, 1.960e+02, 2.000e+00, 3.500e+03],
       [5.090e+01, 1.790e+01, 1.960e+02, 2.000e+00, 3.675e+03],
       [5.080e+01, 1.850e+01, 2.010e+02, 2.000e+00, 4.450e+03],
       [5.010e+01, 1.790e+01, 1.900e+02, 2.000e+00, 3.400e+03],
       [4.900e+01, 1.960e+01, 2.120e+02, 2.000e+00, 4.300e+03],
       [5.150e+01, 1.870e+01, 1.870e+02, 2.000e+00, 3.250e+03],
       [4.980e+01, 1.730e+01, 1.980e+02, 2.000e+00, 3.675e+03],
       [4.610e+01, 1.320e+01, 2.110e+02, 1.000e+00, 4.500e+03],
       [5.000e+01, 1.630e+01, 2.300e+02, 1.000e+00, 5.700e+03],
       [4.870e+01, 1.410e+01, 2.100e+02, 1.000e+00, 4.450e+03],
       [5.000e+01, 1.520e+01, 2.180e+02, 1.000e+00, 5.700e+03],
       [4.760e+01, 1.450e+01, 2.150e+02, 1.000e+00, 5.400e+03],
       [4.650e+01, 1.350e+01, 2.100e+02, 1.000e+00, 4.550e+03],
       [4.540e+01, 1.460e+01, 2.110e+02, 1.000e+00, 4.800e+03],
       [4.670e+01, 1.530e+01, 2.190e+02, 1.000e+00, 5.200e+03],
       [4.330e+01, 1.340e+01, 2.090e+02, 1.000e+00, 4.400e+03],
       [4.680e+01, 1.540e+01, 2.150e+02, 1.000e+00, 5.150e+03],
       [4.090e+01, 1.370e+01, 2.140e+02, 1.000e+00, 4.650e+03],
       [4.900e+01, 1.610e+01, 2.160e+02, 1.000e+00, 5.550e+03],
       [4.550e+01, 1.370e+01, 2.140e+02, 1.000e+00, 4.650e+03],
       [4.840e+01, 1.460e+01, 2.130e+02, 1.000e+00, 5.850e+03],
       [4.580e+01, 1.460e+01, 2.100e+02, 1.000e+00, 4.200e+03],
       [4.930e+01, 1.570e+01, 2.170e+02, 1.000e+00, 5.850e+03],
       [4.200e+01, 1.350e+01, 2.100e+02, 1.000e+00, 4.150e+03],
       [4.920e+01, 1.520e+01, 2.210e+02, 1.000e+00, 6.300e+03],
       [4.620e+01, 1.450e+01, 2.090e+02, 1.000e+00, 4.800e+03],
       [4.870e+01, 1.510e+01, 2.220e+02, 1.000e+00, 5.350e+03],
       [5.020e+01, 1.430e+01, 2.180e+02, 1.000e+00, 5.700e+03],
       [4.510e+01, 1.450e+01, 2.150e+02, 1.000e+00, 5.000e+03],
       [4.650e+01, 1.450e+01, 2.130e+02, 1.000e+00, 4.400e+03],
       [4.630e+01, 1.580e+01, 2.150e+02, 1.000e+00, 5.050e+03],
       [4.290e+01, 1.310e+01, 2.150e+02, 1.000e+00, 5.000e+03],
       [4.610e+01, 1.510e+01, 2.150e+02, 1.000e+00, 5.100e+03],
       [4.450e+01, 1.430e+01, 2.160e+02, 1.000e+00, 4.100e+03],
       [4.780e+01, 1.500e+01, 2.150e+02, 1.000e+00, 5.650e+03],
       [4.820e+01, 1.430e+01, 2.100e+02, 1.000e+00, 4.600e+03],
       [5.000e+01, 1.530e+01, 2.200e+02, 1.000e+00, 5.550e+03],
       [4.730e+01, 1.530e+01, 2.220e+02, 1.000e+00, 5.250e+03],
       [4.280e+01, 1.420e+01, 2.090e+02, 1.000e+00, 4.700e+03],
       [4.510e+01, 1.450e+01, 2.070e+02, 1.000e+00, 5.050e+03],
       [5.960e+01, 1.700e+01, 2.300e+02, 1.000e+00, 6.050e+03],
       [4.910e+01, 1.480e+01, 2.200e+02, 1.000e+00, 5.150e+03],
       [4.840e+01, 1.630e+01, 2.200e+02, 1.000e+00, 5.400e+03],
       [5.050e+01, 1.520e+01, 2.160e+02, 1.000e+00, 5.000e+03],
       [4.980e+01, 1.590e+01, 2.290e+02, 1.000e+00, 5.950e+03],
       [4.350e+01, 1.520e+01, 2.130e+02, 1.000e+00, 4.650e+03],
       [5.150e+01, 1.630e+01, 2.300e+02, 1.000e+00, 5.500e+03],
       [4.620e+01, 1.410e+01, 2.170e+02, 1.000e+00, 4.375e+03],
       [5.510e+01, 1.600e+01, 2.300e+02, 1.000e+00, 5.850e+03],
       [4.450e+01, 1.570e+01, 2.170e+02, 1.000e+00, 4.875e+03],
       [4.880e+01, 1.620e+01, 2.220e+02, 1.000e+00, 6.000e+03],
       [4.720e+01, 1.370e+01, 2.140e+02, 1.000e+00, 4.925e+03],
       [4.680e+01, 1.430e+01, 2.150e+02, 1.000e+00, 4.850e+03],
       [5.040e+01, 1.570e+01, 2.220e+02, 1.000e+00, 5.750e+03],
       [4.520e+01, 1.480e+01, 2.120e+02, 1.000e+00, 5.200e+03],
       [4.990e+01, 1.610e+01, 2.130e+02, 1.000e+00, 5.400e+03]])

In [32]:
#normalize the data
scaler = StandardScaler()
x = scaler.fit_transform(x)